# Aula 3 — Áreas gerais de formação na graduação (IBGE)

**Tabela 3** — Pessoas com nível superior completo, por áreas gerais de formação do curso de graduação concluído, por sexo, segundo Brasil, Grandes Regiões e Unidades da Federação.
Fonte: IBGE — Censo Demográfico.

**Objetivo:** dividir a tabela em 3, com homens e mulheres por região:
1. com curso superior (total)
2. com curso nas áreas de **Ciência, Tecnologia, Engenharias e Matemática**
3. com curso nas áreas de **Educação, Serviços pessoais, Saúde e Bem-estar**

Depois salvar cada uma em `.xlsx` e apresentar as estatísticas com `describe()`.

In [1]:
# No terminal, uma vez: python -m pip install pandas openpyxl
import pandas as pd

In [2]:
# arquivo na mesma pasta do notebook
path = "Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

## Olhando o arquivo bruto

Assim como na aula anterior, o arquivo do IBGE tem **título**, cabeçalho em **duas linhas** e **fonte no rodapé**.

In [3]:
bruto = pd.read_excel(path, header=None)
bruto

,0,1,2,3,4,5,6,7,8,9
0,Tabela 10063 - Pessoas com nível superior comp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Brasil, Grande Região e Unidade da Federação",Total,NaN,NaN,"Ciência, Tecnologia, Engenharias e Matemática",NaN,NaN,"Educação, Serviços pessoais, Saúde e Bem-estar",NaN,NaN
2,NaN,Total,Homens,Mulheres,Total,Homens,Mulheres,Total,Homens,Mulheres
3,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
4,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
5,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
6,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
7,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
8,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
9,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
10,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
11,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
12,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
13,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
14,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
15,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
16,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
17,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
18,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
19,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
20,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
21,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
22,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
23,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
24,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
25,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
26,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
27,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
28,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
29,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
30,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
31,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
32,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
33,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
34,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
35,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538
36,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Limpando a tabela

- Linhas 0–2: título e cabeçalho  |  3–35: dados  |  36: fonte
- Cada área tem 3 colunas: Total, Homens, Mulheres

In [4]:
tabela_3 = bruto.iloc[3:36].copy()
tabela_3.columns = [
    "regiao",
    "superior_total", "superior_homens", "superior_mulheres",
    "ctem_total", "ctem_homens", "ctem_mulheres",
    "educacao_saude_total", "educacao_saude_homens", "educacao_saude_mulheres",
]
tabela_3 = tabela_3.reset_index(drop=True)

# garante que os números são numéricos
for col in tabela_3.columns[1:]:
    tabela_3[col] = pd.to_numeric(tabela_3[col], errors="coerce").astype(int)

tabela_3

,regiao,superior_total,superior_homens,superior_mulheres,ctem_total,ctem_homens,ctem_mulheres,educacao_saude_total,educacao_saude_homens,educacao_saude_mulheres
0,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
1,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
2,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
3,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
4,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
5,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
6,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
7,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
8,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
9,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
10,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
11,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
12,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
13,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
14,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
15,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
16,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
17,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
18,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
19,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
20,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
21,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
22,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
23,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
24,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
25,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
26,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
27,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
28,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
29,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
30,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
31,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
32,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538

## Filtrando só as Grandes Regiões

O pedido é **por região**, então ficamos só com Norte, Nordeste, Sudeste, Sul e Centro-Oeste.
A linha *Brasil* fica de fora porque é a soma das regiões e distorceria as estatísticas do `describe()`.

In [5]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

por_regiao = tabela_3[tabela_3["regiao"].isin(regioes)].reset_index(drop=True)
por_regiao

,regiao,superior_total,superior_homens,superior_mulheres,ctem_total,ctem_homens,ctem_mulheres,educacao_saude_total,educacao_saude_homens,educacao_saude_mulheres
0,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
1,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
2,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
3,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
4,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101

## Tabela 1 — Homens e mulheres por região com curso superior

In [6]:
curso_superior = por_regiao[["regiao", "superior_homens", "superior_mulheres"]].rename(
    columns={"superior_homens": "homens", "superior_mulheres": "mulheres"}
)
curso_superior

         regiao   homens  mulheres
0         Norte   590558    934609
1      Nordeste  1744994   3003939
2       Sudeste  5391638   7437191
3           Sul  1768855   2570005
4  Centro-Oeste   982489   1430013

## Tabela 2 — Homens e mulheres por região com curso em Ciência, Tecnologia, Engenharias e Matemática

In [7]:
tecnologia = por_regiao[["regiao", "ctem_homens", "ctem_mulheres"]].rename(
    columns={"ctem_homens": "homens", "ctem_mulheres": "mulheres"}
)
tecnologia

         regiao   homens  mulheres
0         Norte   133055     76601
1      Nordeste   389993    231395
2       Sudeste  1588874    739247
3           Sul   427372    235543
4  Centro-Oeste   211124    115834

## Tabela 3 — Homens e mulheres por região com curso em Educação, Serviços pessoais, Saúde e Bem-estar

In [8]:
educacao_saude = por_regiao[["regiao", "educacao_saude_homens", "educacao_saude_mulheres"]].rename(
    columns={"educacao_saude_homens": "homens", "educacao_saude_mulheres": "mulheres"}
)
educacao_saude

         regiao  homens  mulheres
0         Norte  141169    458616
1      Nordeste  363905   1458181
2       Sudeste  768288   2884108
3           Sul  248574   1007718
4  Centro-Oeste  156048    593101

## Salvando as 3 tabelas em `.xlsx`

Os arquivos são salvos na mesma pasta do notebook.

In [9]:
curso_superior.to_excel("curso_superior.xlsx", index=False)
tecnologia.to_excel("tecnologia.xlsx", index=False)
educacao_saude.to_excel("educacao_saude.xlsx", index=False)

print("Arquivos salvos: curso_superior.xlsx, tecnologia.xlsx, educacao_saude.xlsx")

Arquivos salvos: curso_superior.xlsx, tecnologia.xlsx, educacao_saude.xlsx

## Estatísticas com `describe()`

O `describe()` mostra, para cada coluna numérica:
- `count` → quantidade de valores (5 regiões)
- `mean` → média
- `std` → desvio padrão (o quanto os valores variam)
- `min` / `max` → menor e maior valor
- `25%`, `50%`, `75%` → quartis (o `50%` é a mediana)

### Curso superior

In [10]:
curso_superior.describe().round(2)

           homens    mulheres
count        5.00        5.00
mean   2095706.80  3075151.40
std    1910348.19  2577597.51
min     590558.00   934609.00
25%     982489.00  1430013.00
50%    1744994.00  2570005.00
75%    1768855.00  3003939.00
max    5391638.00  7437191.00

### Ciência, Tecnologia, Engenharias e Matemática

In [11]:
tecnologia.describe().round(2)

           homens   mulheres
count        5.00       5.00
mean    550083.60  279724.00
std     593417.87  266255.48
min     133055.00   76601.00
25%     211124.00  115834.00
50%     389993.00  231395.00
75%     427372.00  235543.00
max    1588874.00  739247.00

### Educação, Serviços pessoais, Saúde e Bem-estar

In [12]:
educacao_saude.describe().round(2)

          homens    mulheres
count       5.00        5.00
mean   335596.80  1280344.80
std    257699.41   977950.63
min    141169.00   458616.00
25%    156048.00   593101.00
50%    248574.00  1007718.00
75%    363905.00  1458181.00
max    768288.00  2884108.00

## Conclusão

In [13]:
tabelas = {
    "Curso superior": curso_superior,
    "Ciência, Tecnologia, Eng. e Matemática": tecnologia,
    "Educação, Serv. pessoais, Saúde e Bem-estar": educacao_saude,
}

for nome, t in tabelas.items():
    h, m = t["homens"].sum(), t["mulheres"].sum()
    print(f"{nome}")
    print(f"  Média por região -> homens: {t['homens'].mean():,.0f} | mulheres: {t['mulheres'].mean():,.0f}")
    print(f"  Mulheres são {m / (h + m) * 100:.1f}% do total\n")

Curso superior
  Média por região -> homens: 2,095,707 | mulheres: 3,075,151
  Mulheres são 59.5% do total

Ciência, Tecnologia, Eng. e Matemática
  Média por região -> homens: 550,084 | mulheres: 279,724
  Mulheres são 33.7% do total

Educação, Serv. pessoais, Saúde e Bem-estar
  Média por região -> homens: 335,597 | mulheres: 1,280,345
  Mulheres são 79.2% do total